' TODO: [REMOVE COMMENT AFTER REVIEW] Declared all variables under AppConst with Const keyword.
Public Module AppConst

    Public Const DELETE_RPT_FORF_MASTER_SQL As String = "
DELETE FROM RPT_FORF_MASTER"

    Public Const DELETE_RPT_EXCPT_SQL As String = "
DELETE FROM RPT_EXCPT"

    Public Const UPDATE_RPT_FORF_MASTER_SQL As String = "
UPDATE RPT_FORF_MASTER A
SET A.TENOR =
  (SELECT CONCAT((LTRIM(SUBSTR(TENOR_CODE, 2, 4), 0)), SUBSTR(TENOR_CODE,1,1))
  FROM RPT_IFP_BILLS_DETAIL_MONTHEND
  WHERE BILLS_REF = A.BILLS_REF)"

    Public Const INSERT_RPT_FORF_MASTER_SQL As String = "
INSERT
INTO RPT_FORF_MASTER
  (
    BILLS_REF,
    TENOR,
    MODEL_TYPE,
    CURRENCY,
    LOAN_PRINCIPAL,
    LOAN_START_DATE,
    LOAN_DUE_DATE,
    INTEREST_RATE
  )
  VALUES
  (
    :BILLS_REF,
    :TENOR,
    :MODEL_TYPE,
    :CURRENCY,
    :LOAN_PRINCIPAL,
    :LOAN_START_DATE,
    :LOAN_DUE_DATE,
    :INTEREST_RATE
  )"

    Public Const SELECT_DATAPREPARE_RPT_FORF_MASTER_SQL As String = "
SELECT B.BILLS_REF,
  CONCAT((LTRIM(SUBSTR(B.TENOR_CODE,2, 4), 0)), SUBSTR(B.TENOR_CODE,1,1)) AS TENOR,
  A.MODEL_TYPE,
  B.BILLS_CCY,
  B.OS_BAL_FCY,
  B.CREATE_DATE,
  B.DUE_DATE,
  B.INT_RATE
FROM
  (SELECT * FROM RPT_FORF_UPLOAD WHERE VALID_IND ='Y'
  )A
INNER JOIN RPT_IFP_BILLS_DETAIL_MONTHEND B
ON TRIM(A.BILLS_REF) = TRIM(B.BILLS_REF)"

    'Insert RPT_FORF_MASTER from rpt_forf_upload And rpt_ifp_bills_detail_monthend 
    'result equals To pass result from DataPrepare_RPT_FORF_MASTER_SQL And insert from 
    Public Const INSERT_RPT_FORF_MASTER_SQL1 As String = "
INSERT
INTO RPT_FORF_MASTER
  (
    BILLS_REF,
    TENOR,
    MODEL_TYPE,
    CURRENCY,
    LOAN_PRINCIPAL,
    LOAN_START_DATE,
    LOAN_DUE_DATE,
    INTEREST_RATE
  )
SELECT
  CASE B.BILLS_REF,
      CONCAT((LTRIM(SUBSTR(B.TENOR_CODE,2, 4), 0)), SUBSTR(B.TENOR_CODE,1,1)) AS TENOR,
      A.MODEL_TYPE,
      B.BILLS_CCY,
      B.OS_BAL_FCY,
      B.CREATE_DATE,
      B.DUE_DATE,
      B.INT_RATE
    FROM
      (SELECT * FROM RPT_FORF_UPLOAD WHERE VALID_IND = 'Y'
      )A
    INNER JOIN RPT_IFP_BILLS_DETAIL_MONTHEND B
    ON TRIM(A.BILLS_REF) = TRIM(B.BILLS_REF) "

    Public Const INSERT_INTO_RPT_EXCPT As String = "
INSERT
INTO RPT_EXCPT
  (
    BILLS_REF,
    ERROR_MESSAGE
  )
  VALUES
  (
    :BILLS_REF,
    :ERROR_MESSAGE
  )"

    Public Const SELECT_BILLS_REF_FROM_RPT_IFP_BILLS_DETAIL_MONTHEND As String = "
SELECT BILLS_REF
FROM RPT_IFP_BILLS_DETAIL_MONTHEND
WHERE TRIM(BILLS_REF) = :BILLS_REF"

    Public Const SELECT_RPT_FORF_UPLOAD_BY_BILLS_REF As String = "
SELECT * FROM RPT_FORF_UPLOAD WHERE TRIM(BILLS_REF) = :BILLS_REF"

    Public Const UPDATE_RPT_FORF_UPLOAD_VALID_IND As String = "
UPDATE RPT_FORF_UPLOAD SET VALID_IND = 'N' WHERE TRIM(BILLS_REF) = :BILLS_REF"

    Public Const SELECT_FROM_RPT_IFP_BILLS_DETAIL_MONTHEND_BY_TENOR_CODE As String = "
SELECT 1
FROM RPT_IFP_BILLS_DETAIL_MONTHEND
WHERE TRIM(BILLS_REF) =:BILLS_REF
AND TENOR_CODE       IS NULL"

    Public Const SELECT_FROM_RPT_REPRICE_UPLOAD_GROUP_BY_BILLS_REF As String = "
SELECT BILLS_REF FROM RPT_REPRICE_UPLOAD GROUP BY BILLS_REF HAVING COUNT(1) >1"

    Public Const SELECT_FROM_RPT_FORF_UPLOAD_BY_MODEL_TYPE As String = "
SELECT * FROM RPT_FORF_UPLOAD WHERE MODEL_TYPE IN ('1','2','3','4')"

    Public Const SELECT_IS_CONTINUE_PERIOD_SQL As String = "
SELECT BILLS_REF
FROM
  (SELECT RPT_REPRICE_UPLOAD.* ,
    CASE
      WHEN (ROWNUM = 1)
      THEN '-1'
      ELSE LAG(TO_CHAR(END_DATE,'yyyymmdd'),1,0) OVER (ORDER BY BILLS_REF,START_DATE,END_DATE)
    END AS PREV_END_DATE
  FROM RPT_REPRICE_UPLOAD
  WHERE BILLS_REF IN ( :BILLS_REF )
  ORDER BY BILLS_REF,
    START_DATE,
    END_DATE
  )
WHERE TO_CHAR(START_DATE,'yyyymmdd')<> PREV_END_DATE
AND PREV_END_DATE                   <>-1
GROUP BY BILLS_REF
HAVING COUNT(1) >0"

    Public Const SELECT_FROM_RPT_FORF_REFN_MONTHEND_RPT_BILLS_DETAIL_MONTHEND_RPT_FORF_UPLOAD As String = "
SELECT A.BILLS_REF
FROM RPT_FORF_REFN_MONTHEND A,
  RPT_BILLS_DETAIL_MONTHEND B,
  RPT_FORF_UPLOAD C
WHERE A.TYPE_IND   = 'F'
AND A.BILLS_REF    = B.BILLS_REF
AND C.BILLS_REF (+)= A.BILLS_REF  AND C.BILLS_REF IS NULL ORDER BY A.BILLS_REF"

    Public Const SELECT_FROM_RPT_FORF_UPLOAD_RPT_IFP_BILLS_DETAIL_MONTHEND As String = "
SELECT A.BILLS_REF,
  B.BILLS_CCY,
  CONCAT((LTRIM(SUBSTR(B.TENOR_CODE,2, 4), 0)), SUBSTR(B.TENOR_CODE,1,1)) AS TENOR,
  A.MODEL_TYPE
FROM RPT_FORF_UPLOAD A ,
  RPT_IFP_BILLS_DETAIL_MONTHEND B
WHERE TRIM(A.BILLS_REF )=TRIM(B.BILLS_REF)"

    Public Const SELECT_FROM_RPT_CURVE_USAGE As String = "
SELECT CURVE_NAME
FROM RPT_CURVE_USAGE
WHERE CURRENCY_CODE = :currencyCode
AND USAGE           = :usage
AND (1              = :skipTenorCodeCondition
OR TENOR_CODE       = :tenorCode)"

    ' TODO: [REMOVE COMMENT AFTER REVIEW] Duplicated functionality with SELECT_FROM_RPT_CURVE_USAGE.
    '    Public Const SELECT_FIND_CURVE_NAME_SQL_F As String = "
    'SELECT CURVE_NAME
    'FROM RPT_CURVE_USAGE
    'WHERE CURVE_NAME IS NOT NULL
    'AND CURRENCY_CODE =:IN_CCY
    'AND USAGE         =:IN_USAGE
    'AND TENOR_CODE    =:IN_TENOR_CODE"

    Public Const SELECT_FROM_RPT_FORF_UPLOAD As String = "
SELECT BILLS_REF, MODEL_TYPE FROM RPT_FORF_UPLOAD"

    Public Const SELECT_FROM_RPT_REPRICE_UPLOAD As String = "
SELECT * FROM RPT_REPRICE_UPLOAD"

    Public Const SELECT_IS_EXIST_IN_REPRICE_SQL As String = "
SELECT * FROM RPT_REPRICE_UPLOAD WHERE TRIM(BILLS_REF) = :BILLS_REF"

    Public Const SELECT_END_DATE_FROM_RPT_REPRICE_UPLOAD As String = "
SELECT MAX(END_DATE) AS END_DATE
FROM RPT_REPRICE_UPLOAD
WHERE TRIM(BILLS_REF) = :BILLS_REF"

    Public Const SELECT_DUE_DATE_FROM_RPT_IFP_BILLS_DETAIL_MONTHEND As String = "
SELECT DUE_DATE AS DUE_DATE
FROM RPT_IFP_BILLS_DETAIL_MONTHEND
WHERE TRIM(BILLS_REF) = :BILLS_REF"

    Public Const DELETE_FROM_RPT_IS9_PROVISION As String = "
DELETE FROM RPT_IS9_PROVISION"

    Public Const INSERT_INTO_RPT_IS9_PROVISION_FROM_RPT_IS9_PROVISION_STG As String = "
INSERT INTO RPT_IS9_PROVISION
SELECT SUBSTR(DEAL_REF,5,10), TOT_PROVISION FROM RPT_IS9_PROVISION_STG"

    ' TODO: [REMOVE COMMENT AFTER REVIEW] Duplicated functionality with Utility.UpdateSwapCurveStartDate.
    '    Public Const UPDATE_RPT_CURVE_USAGE_SQL As String = "
    'UPDATE RPT_SWAP_CURVE
    'SET START_DATE =
    '  (SELECT MONTHEND_DATE FROM RPT_RUN_DATE_MONTHEND
    '  )"

    Public Const UPDATE_RPT_SWAP_CURVE_SQL As String = "
UPDATE RPT_SWAP_CURVE
SET START_DATE =
  (SELECT MONTHEND_DATE FROM RPT_RUN_DATE_MONTHEND
  )"

    Public Const SELECT_RPT_SWAP_CURVE_SQL As String = "
SELECT DISTINCT CURVE_NAME
  || ' ('
  || CURRENCY_CODE
  || ')' AS CURVE_NAME
FROM RPT_SWAP_CURVE
WHERE CURVE_NAME
  || CURRENCY_CODE NOT IN
  (SELECT DISTINCT CURVE_NAME || CURRENCY_CODE FROM RPT_CURVE_USAGE
  )
"

    Public Const UPDATE_RPT_SWAP_CURVE_CURRENCY_SQL As String = "
UPDATE RPT_SWAP_CURVE SET CURRENCY_CODE = 'CNY' WHERE CURRENCY_CODE = 'CNH'
"
End Module