Load Data
INFILE "RPT_FORF_UPLOAD.csv"
BADFILE "RPT_FORF_UPLOAD.BAD"
DISCARDFILE "RPT_FORF_UPLOAD.DSC"
TRUNCATE
INTO TABLE RPT_FORF_UPLOAD
FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  BILLS_REF ,
  MODEL_TYPE
)
