Load Data
INFILE "RPT_CURVE_USAGE.csv"
BADFILE "RPT_CURVE_USAGE.BAD"
DISCARDFILE "RPT_CURVE_USAGE.DSC"
TRUNCATE
INTO TABLE TEST_RPT_CURVE_USAGE
FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
CURVE_NAME ,
CURRENCY_CODE ,
TENOR_CODE ,
USAGE  
)
