Load Data
INFILE "RPT_REPRICE_UPLOAD.csv"
BADFILE "RPT_REPRICE_UPLOAD.BAD"
DISCARDFILE "RPT_REPRICE_UPLOAD.DSC"
TRUNCATE
INTO TABLE TEST_RPT_REPRICE_UPLOAD
FIELDS TERMINATED BY "," OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  BILLS_REF,
  START_DATE date "yyyyMMdd" , 
   END_DATE   date "yyyyMMdd" 
)
