Public Module AppConst


    Public Const DELETE_FROM_ARR As String = "
DELETE FROM ARR_RATE
WHERE    RUN_DATE = (SELECT RUN_DATE FROM RUN_DATE    )
"
    Friend INSERT_INTO_ARR As String = "
INSERT INTO ARR_RATE (
RATE_CODE	,
FCC	,
CONVENT_TYPE	,
K_DAYS	,
END_DATE	,
START_DATE	,
DAYS_OF_INT	,
COMP_RATE_UNADJ	,
SIM_RATE_UNADJ	,
COMP_RATE_ADJ	,
SIM_RATE_ADJ	,
FLOOR_RATE	,
FLOOR_IND	,
COMP_RATE_ADJ_CAS_ON	,
SIM_RATE_ADJ_CAS_ON	,
FLOOR_IND_CAS_ON	,
COMP_RATE_ADJ_CAS_1W	,
SIM_RATE_ADJ_CAS_1W	,
FLOOR_IND_CAS_1W	,
COMP_RATE_ADJ_CAS_1M	,
SIM_RATE_ADJ_CAS_1M	,
FLOOR_IND_CAS_1M	,
COMP_RATE_ADJ_CAS_2M	,
SIM_RATE_ADJ_CAS_2M	,
FLOOR_IND_CAS_2M	,
COMP_RATE_ADJ_CAS_3M	,
SIM_RATE_ADJ_CAS_3M	,
FLOOR_IND_CAS_3M	,
COMP_RATE_ADJ_CAS_6M	,
SIM_RATE_ADJ_CAS_6M	,
FLOOR_IND_CAS_6M	,
COMP_RATE_ADJ_CAS_12M	,
SIM_RATE_ADJ_CAS_12M	,
FLOOR_IND_CAS_12M	,
RUN_DATE	
) VALUES (
:RATE_CODE,
:FCC,
:CONVENT_TYPE,
:K_DAYS,
:END_DATE,
:START_DATE,
:DAYS_OF_INT,
:COMP_RATE_UNADJ,
:SIM_RATE_UNADJ,
:COMP_RATE_ADJ,
:SIM_RATE_ADJ,
:FLOOR_RATE,
:FLOOR_IND,
:COMP_RATE_ADJ_CAS_ON,
:SIM_RATE_ADJ_CAS_ON,
:FLOOR_IND_CAS_ON,
:COMP_RATE_ADJ_CAS_1W,
:SIM_RATE_ADJ_CAS_1W,
:FLOOR_IND_CAS_1W,
:COMP_RATE_ADJ_CAS_1M,
:SIM_RATE_ADJ_CAS_1M,
:FLOOR_IND_CAS_1M,
:COMP_RATE_ADJ_CAS_2M,
:SIM_RATE_ADJ_CAS_2M,
:FLOOR_IND_CAS_2M,
:COMP_RATE_ADJ_CAS_3M,
:SIM_RATE_ADJ_CAS_3M,
:FLOOR_IND_CAS_3M,
:COMP_RATE_ADJ_CAS_6M,
:SIM_RATE_ADJ_CAS_6M,
:FLOOR_IND_CAS_6M,
:COMP_RATE_ADJ_CAS_12M,
:SIM_RATE_ADJ_CAS_12M,
:FLOOR_IND_CAS_12M,
:RUN_DATE
)
"

End Module
